const item_list = [
    {item_no:1, section:'여성신발', src:'dunk (1).png', title:'덩크로우 핑크', price:'134,000원', color:'1개의 색상',},
    {item_no:2, section:'여성신발', src:'dunk (2).png', title:'덩크로우 검노', price:'112,000원', color:'1개의 색상',},
    {item_no:3, section:'여성신발', src:'dunk (3).png', title:'덩크로우 그레이', price:'134,000원', color:'1개의 색상',},
    {item_no:4, section:'남성신발', src:'dunk (4).png', title:'덩크로우 와인', price:'123,000원', color:'1개의 색상',},
    {item_no:5, section:'여성신발', src:'dunk (5).png', title:'덩크로우 바닐라', price:'122,000원', color:'1개의 색상',},
    {item_no:6, section:'여성신발', src:'dunk (6).png', title:'덩크로우 범고래', price:'141,000원', color:'1개의 색상',},
    {item_no:7, section:'여성신발', src:'dunk (7).png', title:'덩크로우 카키', price:'121,000원', color:'1개의 색상',},
    {item_no:8, section:'남성신발', src:'dunk (8).png', title:'덩크로우 회핑', price:'132,000원', color:'1개의 색상',},
    {item_no:9, section:'여성신발', src:'dunk (9).png', title:'덩크로우 빨노주', price:'143,000원', color:'1개의 색상',},
    {item_no:10, section:'남성신발', src:'dunk (10).png', title:'덩크로우 흰하', price:'111,000원', color:'1개의 색상',},
    {item_no:11, section:'여성신발', src:'dunk (11).png', title:'덩크로우 머스타드', price:'123,000원', color:'1개의 색상',},
    {item_no:12, section:'남성신발', src:'dunk (12).png', title:'덩크로우 오렌지', price:'132,000원', color:'1개의 색상',},
    {item_no:13, section:'남성신발', src:'dunk (13).png', title:'덩크로우 검주', price:'142,000원', color:'1개의 색상',},
    {item_no:14, section:'남성신발', src:'dunk (14).png', title:'덩크로우 에메랄드', price:'112,000원', color:'1개의 색상',},
    {item_no:15, section:'남성신발', src:'dunk (15).png', title:'덩크로우 군화', price:'132,000원', color:'1개의 색상',},
    {item_no:16, section:'남성신발', src:'dunk (16).png', title:'덩크로우 발렌타인', price:'123,000원', color:'1개의 색상',},
    {item_no:17, section:'여성신발', src:'dunk (17).png', title:'덩크로우 생노', price:'143,000원', color:'1개의 색상',},
    {item_no:18, section:'남성신발', src:'dunk (18).png', title:'덩크로우 된장', price:'121,000원', color:'1개의 색상',},
    {item_no:19, section:'남성신발', src:'dunk (19).png', title:'덩크로우 화이트크림', price:'112,000원', color:'1개의 색상',},
    {item_no:20, section:'여성신발', src:'dunk (20).png', title:'덩크로우 파스텔', price:'132,000원', color:'1개의 색상',},
    {item_no:21, section:'여성신발', src:'dunk (21).png', title:'덩크로우 누끼', price:'142,000원', color:'1개의 색상',},
    {item_no:22, section:'남성신발', src:'dunk (22).png', title:'덩크로우 페이던트', price:'123,000원', color:'1개의 색상',},
] 